{% set version = "0.7.2" %}

package:
  name: trajopt-pkg
  version: {{ version }}

source:
  - url: https://github.com/tesseract-robotics/trajopt/archive/refs/tags/{{ version }}.tar.gz
    sha256: ffea3b303b605928202227f81a224aada2b7fe5b50811cfd6f032f132e9fbc89
    folder: src/trajopt
    patches:
      - trajopt-patch.patch

build:
  number: 1

outputs:
  - name: trajopt-common
    build:
      script_env:
        - SUBPKG_SRC_DIR=src/trajopt/trajopt_common
        - SUBPKG_BUILD_DIR=build/trajopt_common
    script: build_pkg.sh # [unix]
    script: bld_pkg.bat # [win]
    version: {{ version }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - gtest
        - gmock
        - cmake
        - ninja # [win]
        - make # [linux]
        - ros-industrial-cmake-boilerplate
      host:
        - eigen
        - console_bridge
        - libboost-devel
        - tesseract-robotics-common
        - tesseract-robotics-collision
        - tesseract-robotics-kinematics
        - ros-industrial-cmake-boilerplate
      run:
        - eigen
        - tesseract-robotics-common
        - tesseract-robotics-collision
        - tesseract-robotics-kinematics
    test:
      commands:
        - test -f ${PREFIX}/include/trajopt_common/utils.hpp  # [unix]
        - test -f ${PREFIX}/lib/cmake/trajopt_common/trajopt_common-config.cmake # [unix]
        - if not exist %LIBRARY_PREFIX%\include\trajopt_common\utils.hpp (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\lib\cmake\trajopt_common\trajopt_common-config.cmake (exit 1)  # [win]
  - name: vhacd
    build:
      script_env:
        - SUBPKG_SRC_DIR=src/trajopt/trajopt_ext/vhacd
        - SUBPKG_BUILD_DIR=build/vhacd
    script: build_pkg.sh # [unix]
    script: bld_pkg.bat # [win]
    version: {{ version }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - gtest
        - gmock
        - cmake
        - ninja # [win]
        - make # [linux]
        - ros-industrial-cmake-boilerplate
      host:
        - eigen
        - console_bridge
        - bullet-cpp
        - libboost-devel
        - ros-industrial-cmake-boilerplate
        - trajopt-common
      run:
        - eigen
        - bullet-cpp
        - trajopt-common
    test:
      commands:
        - test -f ${PREFIX}/include/vhacd/VHACD.h  # [unix]
        - test -f ${PREFIX}/lib/libvhacd.so  # [unix]
        - test -f ${PREFIX}/lib/cmake/vhacd/vhacd-config.cmake # [unix]
        - if not exist %LIBRARY_PREFIX%\include\vhacd\VHACD.h (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\lib\vhacd.lib (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\bin\vhacd.dll (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\lib\cmake\vhacd\vhacd-config.cmake (exit 1)  # [win]
  - name: trajopt-sco
    build:
      script_env:
        - SUBPKG_SRC_DIR=src/trajopt/trajopt_sco
        - SUBPKG_BUILD_DIR=build/trajopt_sco
    script: build_pkg.sh # [unix]
    script: bld_pkg.bat # [win]
    version: {{ version }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - gtest
        - gmock
        - cmake
        - ninja # [win]
        - make # [linux]
        - ros-industrial-cmake-boilerplate
      host:
        - eigen
        - console_bridge
        - libboost-devel
        - jsoncpp
        - osqp
        - qpoases
        - ros-industrial-cmake-boilerplate
        - trajopt-common
      run:
        - eigen
        - jsoncpp
        - console_bridge
        - osqp
        - qpoases
        - trajopt-common
  - name: trajopt
    build:
      script_env:
        - SUBPKG_SRC_DIR=src/trajopt/trajopt
        - SUBPKG_BUILD_DIR=build/trajopt
    script: build_pkg.sh # [unix]
    script: bld_pkg.bat # [win]
    version: {{ version }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - gtest
        - gmock
        - cmake
        - ninja # [win]
        - make # [linux]
        - ros-industrial-cmake-boilerplate
        - pkg-config
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
      host:
        - eigen
        - console_bridge
        - libboost-devel
        - trajopt-common
        - trajopt-sco
        - ros-industrial-cmake-boilerplate
        - tesseract-robotics-environment
        - tesseract-robotics-visualization
        - jsoncpp
      run:
        - eigen
        - console_bridge
        - trajopt-common
        - trajopt-sco
        - tesseract-robotics-environment
        - tesseract-robotics-visualization
        - jsoncpp
    test:
      commands:
        - test -f ${PREFIX}/include/trajopt/common.hpp  # [unix]
        - test -f ${PREFIX}/lib/libtrajopt.so  # [unix]
        - test -f ${PREFIX}/lib/cmake/trajopt/trajopt-config.cmake # [unix]
        - if not exist %LIBRARY_PREFIX%\include\trajopt\common.hpp (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\lib\trajopt.lib (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\bin\trajopt.dll (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\lib\cmake\trajopt\trajopt-config.cmake (exit 1)  # [win]

about:
  home: https://github.com/tesseract-robotics/trajopt
  summary: Trajectory Optimization Motion Planner
  license: BSD-2-Clause
  license_file: src/trajopt/trajopt/LICENSE

extra:
  recipe-maintainers:
    - johnwason