package:
  name: trajopt
  version: 0.2.2

source:
  - git_url: https://github.com/tesseract-robotics/trajopt.git
    git_rev: 0.2.2

build:
  number: 0

outputs:
  - name: vhacd
    script: build_vhacd.sh # [unix]
    script: bld_vhacd.bat # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - gtest
        - gmock
        - cmake
        - ninja # [win]
        - make # [linux]
        - ros-industrial-cmake-boilerplate
        - eigen
        - console_bridge
        - boost
        - tesseract-robotics-util
      run:
        - eigen
        - bullet
        - tesseract-robotics-util

about:
  home: https://github.com/tesseract-robotics/trajopt
  summary: Trajectory Optimization Motion Planner